### PR TITLE
Update Axum examples to latest 0.6 release and streamline them a bit

### PR DESCRIPTION
**Pull request by benwis**
Hi,
I updated the Axum examples to the latest 0.6 release and did a bit of housecleaning.
This should address #138

### CODE REVIEW

**Comment by gbj** [comment]
Thanks so much. I still have no idea what's going on with the CI on GitHub but assuming this passes on my local CI run I'll merge it. I really appreciate it.

**Comment by gbj** [comment]
@benwis I'm getting some errors when I run `cargo test` in `integrations/axum`, which are suggesting that either the implementation is a little off or the doctest is a little off. Could you take a look?

```
... view! { cx, <MyApp/> }).into_service());
    |                             ^^^^^^^^^^^^ method not found in `impl (Fn(axum::http::Request<Body>) -> Pin<Box<(dyn Future<Output = StreamBody<Pin<Box<(dyn futures_core::stream::Stream<Item = Result<axum::body::Bytes, std::io::Error>> + Send + 'static)>>>> + Send + 'static)>>) + Clone + Send + 'static`
    |
   ::: /Users/gjohnston/.cargo/registry/src/github.com-1ecc6299db9ec823/axum-0.6.1/src/handler/mod.rs:302:8
    |
302 |     fn into_service(self) -> HandlerService<Self, T, (), B>;
    |        ------------ the method is available for `impl (Fn(axum::http::Request<Body>) -> Pin<Box<(dyn Future<Output = StreamBody<Pin<Box<(dyn futures_core::stream::Stream<Item = Result<axum::body::Bytes, std::io::Error>> + Send + 'static)>>>> + Send + 'static)>>) + Clone + Send + 'static` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
2   | use axum::handler::HandlerWithoutStateExt;
```

If I add `HandlerWithoutStateExt` to the handler import in the doctest, I get

```
error[E0277]: the trait bound `HandlerService<impl (Fn(axum::http::Request<Body>) -> Pin<Box<(dyn Future<Output = StreamBody<Pin<Box<(dyn futures_core::stream::Stream<Item = Result<axum::body::Bytes, std::io::Error>> + Send + 'static)>>>> + Send + 'static)>>) + Clone + Send + 'static, (axum_core::extract::private::ViaRequest, axum::http::Request<Body>), (), Body>: Handler<_, _, _>` is not satisfied
   --> src/lib.rs:160:15
    |
21  |     .fallback(leptos_axum::render_app_to_stream("leptos_example", |cx| view! { cx, <MyApp/> }).into_service(...
    |      -------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Handler<_, _, _>` is not implemented for `HandlerService<impl (Fn(axum::http::Request<Body>) -> Pin<Box<(dyn Future<Output = StreamBody<Pin<Box<(dyn futures_core::stream::Stream<Item = Result<axum::body::Bytes, std::io::Error>> + Send + 'static)>>>> + Send + 'static)>>) + Clone + Send + 'static, (axum_core::extract::private::ViaRequest, axum::http::Request<Body>), (), Body>`
    |      |
    |      required by a bound introduced by this call
```

**Comment by benwis** [comment]
@gbj Are you sure you're in the right branch? `cargo check` in integrations/axum builds normally for me

**Comment by gbj** [comment]
Looks good to me!

**Pull request merged**
